name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - releases/*
  pull_request:
    branches:
      - develop
      - releases/*

jobs:
  build-and-scan:
    name: Build & Scan Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          echo "Building docker image"

      - name: Run Code Scanning (Snyk)
        run: |
          echo "Code scanning"

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch k8s kubeconfig of dev's cluster
        run: |
          echo "Getting kubeconfig (dev)"

      - name: Deploy to Dev
        run: |
          echo "Deploying to dev env"

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: startsWith(github.ref, 'refs/heads/releases/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name:  Fetch k8s kubeconfig of staging's cluster
        run: |
          echo "Getting kubeconfig (staging)"

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging env"

  deploy-uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: UAT  # Enforces manual approval before proceeding
    if: startsWith(github.ref, 'refs/heads/releases/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch k8s kubeconfig of UAT's cluster
        run: |
          echo "Getting kubeconfig (UAT)"

      - name: Deploy to UAT
        run: |
          echo "Deploying to UAT env"
