name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - releases/*
  pull_request:
    branches:
      - develop
      - releases/*

jobs:
  build-and-scan:
    name: Build & Scan Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          echo "Building docker image"

      - name: Run Code Scanning (Snyk)
        run: |
          echo "Code scanning"

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch k8s kubeconfig of dev's cluster
        run: |
          echo "Getting kubeconfig (dev)"
          echo "Getting environment variables"
          env

      - name: Deploy to Dev
        run: |
          echo "Deploying to dev env"
          env

  deploy-uat:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: startsWith(github.ref, 'refs/heads/releases/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name:  Fetch k8s kubeconfig of UAT's cluster
        run: |
          echo "Getting kubeconfig (uat)"
          echo "Getting environment variables"
          env

      - name: Deploy to Staging
        run: |
          echo "Deploying to uat env"
          echo "Getting environment variables"
          env

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-uat
    environment: PRODUCTION  # Enforces manual approval before proceeding
    if: startsWith(github.ref, 'refs/heads/releases/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch k8s kubeconfig of PROD's cluster
        run: |
          echo "Getting kubeconfig (PROD)"
          echo "Getting environment variables"
          env

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD env"
          echo "Getting environment variables"
          env
